# Generated by Django 6.1 on 2026-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
