# Generated by Django 6.1 on 2026-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='journal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
