# Generated by Django 6.1 on 2026-09-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_company'),
        ('main', '0007_coursework_journal'),
    ]

    operations = [
    ]
