# Generated by Django 6.1 on 2026-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_0004_experience_company_0007_coursework_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organizational', 'Organizational')], default='full-time', max_length=20),
        ),
    ]
